name: Scrape and push 

on: 
  schedule: 
    - cron: "0 0 * * *"
    # runs daily at midnight
  workflow_dispatch:

env: 
  EMAIL: ${{ secrets.EMAIL }}
  NAME: ${{ secrets.NAME }}

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Scrape
        run: python3 scrape-esdj.py
        shell: bash

      - name: Save Time
        run: | 
          echo "TIME=$(TZ=America/Los_Angeles date +'%m/%d/%Y %H:%M %Z')" >> $GITHUB_ENV
          # echo "time2=$(date +"%Y-%m-%d")" >> $GITHUB_ENV

      - name: Commit files
        run: |
          git config --local user.email ${{ env.EMAIL }}
          git config --local user.name ${{ env.NAME }}
          git commit -a -m "adding new jobs on ${{ env.TIME }}"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      # - run: echo "🍏 This job's status is ${{ job.status }}."